package com.weather.backend.util;

public class SampleResponseJson {
    private SampleResponseJson() {

    }

    public static final String SCHEMA_200 = """
            {
               "cod": "200",
               "message": null,
               "data": {
                 "cnt": 40,
                 "list": [
                   {
                     "dtTxt": "2025-01-20 15:00:00",
                     "summary": "Clear",
                     "description": "clear sky",
                     "temp": 19.42,
                     "pressure": 1012,
                     "humidity": 43,
                     "tempMin": 19.42,
                     "tempMax": 19.42,
                     "tempFeelsLike": 18.54,
                     "visibility": 10000,
                     "windSpeed": 4.52,
                     "cloudPercentage": 0,
                     "icon": "01n",
                     "advice": "Cool weather, wear a light jacket!"
                   },
                   {
                     "dtTxt": "2025-01-20 18:00:00",
                     "summary": "Clear",
                     "description": "clear sky",
                     "temp": 17.3,
                     "pressure": 1013,
                     "humidity": 49,
                     "tempMin": 17.3,
                     "tempMax": 17.3,
                     "tempFeelsLike": 16.37,
                     "visibility": 10000,
                     "windSpeed": 3.66,
                     "cloudPercentage": 0,
                     "icon": "01n",
                     "advice": "Cool weather, wear a light jacket!"
                   },
                   {
                     "dtTxt": "2025-01-20 21:00:00",
                     "summary": "Clear",
                     "description": "clear sky",
                     "temp": 15.01,
                     "pressure": 1013,
                     "humidity": 56,
                     "tempMin": 15.01,
                     "tempMax": 15.01,
                     "tempFeelsLike": 14.03,
                     "visibility": 10000,
                     "windSpeed": 3.2,
                     "cloudPercentage": 0,
                     "icon": "01n",
                     "advice": "Cool weather, wear a light jacket!"
                   },
                   {
                     "dtTxt": "2025-01-21 00:00:00",
                     "summary": "Clear",
                     "description": "clear sky",
                     "temp": 13.99,
                     "pressure": 1013,
                     "humidity": 62,
                     "tempMin": 13.99,
                     "tempMax": 13.99,
                     "tempFeelsLike": 13.06,
                     "visibility": 10000,
                     "windSpeed": 3.23,
                     "cloudPercentage": 0,
                     "icon": "01n",
                     "advice": "Cool weather, wear a light jacket!"
                   },
                   {
                     "dtTxt": "2025-01-21 03:00:00",
                     "summary": "Clear",
                     "description": "clear sky",
                     "temp": 19.45,
                     "pressure": 1014,
                     "humidity": 49,
                     "tempMin": 19.45,
                     "tempMax": 19.45,
                     "tempFeelsLike": 18.73,
                     "visibility": 10000,
                     "windSpeed": 5.02,
                     "cloudPercentage": 0,
                     "icon": "01d",
                     "advice": "Cool weather, wear a light jacket!"
                   },
                   {
                     "dtTxt": "2025-01-21 06:00:00",
                     "summary": "Clear",
                     "description": "clear sky",
                     "temp": 26.33,
                     "pressure": 1013,
                     "humidity": 23,
                     "tempMin": 26.33,
                     "tempMax": 26.33,
                     "tempFeelsLike": 26.33,
                     "visibility": 10000,
                     "windSpeed": 5.9,
                     "cloudPercentage": 0,
                     "icon": "01d",
                     "advice": "clear sky"
                   },
                   {
                     "dtTxt": "2025-01-21 09:00:00",
                     "summary": "Clear",
                     "description": "clear sky",
                     "temp": 28.61,
                     "pressure": 1010,
                     "humidity": 17,
                     "tempMin": 28.61,
                     "tempMax": 28.61,
                     "tempFeelsLike": 27.11,
                     "visibility": 10000,
                     "windSpeed": 5.35,
                     "cloudPercentage": 0,
                     "icon": "01d",
                     "advice": "clear sky"
                   },
                   {
                     "dtTxt": "2025-01-21 12:00:00",
                     "summary": "Clear",
                     "description": "clear sky",
                     "temp": 22.08,
                     "pressure": 1011,
                     "humidity": 26,
                     "tempMin": 22.08,
                     "tempMax": 22.08,
                     "tempFeelsLike": 21.02,
                     "visibility": 10000,
                     "windSpeed": 3.97,
                     "cloudPercentage": 0,
                     "icon": "01n",
                     "advice": "clear sky"
                   },
                   {
                     "dtTxt": "2025-01-21 15:00:00",
                     "summary": "Clear",
                     "description": "clear sky",
                     "temp": 19.18,
                     "pressure": 1013,
                     "humidity": 30,
                     "tempMin": 19.18,
                     "tempMax": 19.18,
                     "tempFeelsLike": 17.94,
                     "visibility": 10000,
                     "windSpeed": 4.01,
                     "cloudPercentage": 0,
                     "icon": "01n",
                     "advice": "Cool weather, wear a light jacket!"
                   },
                   {
                     "dtTxt": "2025-01-21 18:00:00",
                     "summary": "Clear",
                     "description": "clear sky",
                     "temp": 17.21,
                     "pressure": 1013,
                     "humidity": 34,
                     "tempMin": 17.21,
                     "tempMax": 17.21,
                     "tempFeelsLike": 15.87,
                     "visibility": 10000,
                     "windSpeed": 4.05,
                     "cloudPercentage": 0,
                     "icon": "01n",
                     "advice": "Cool weather, wear a light jacket!"
                   },
                   {
                     "dtTxt": "2025-01-21 21:00:00",
                     "summary": "Clear",
                     "description": "clear sky",
                     "temp": 16.13,
                     "pressure": 1012,
                     "humidity": 40,
                     "tempMin": 16.13,
                     "tempMax": 16.13,
                     "tempFeelsLike": 14.84,
                     "visibility": 10000,
                     "windSpeed": 3.63,
                     "cloudPercentage": 0,
                     "icon": "01n",
                     "advice": "Cool weather, wear a light jacket!"
                   },
                   {
                     "dtTxt": "2025-01-22 00:00:00",
                     "summary": "Clear",
                     "description": "clear sky",
                     "temp": 15.02,
                     "pressure": 1013,
                     "humidity": 48,
                     "tempMin": 15.02,
                     "tempMax": 15.02,
                     "tempFeelsLike": 13.83,
                     "visibility": 10000,
                     "windSpeed": 3.57,
                     "cloudPercentage": 0,
                     "icon": "01n",
                     "advice": "Cool weather, wear a light jacket!"
                   },
                   {
                     "dtTxt": "2025-01-22 03:00:00",
                     "summary": "Clear",
                     "description": "clear sky",
                     "temp": 20.81,
                     "pressure": 1015,
                     "humidity": 36,
                     "tempMin": 20.81,
                     "tempMax": 20.81,
                     "tempFeelsLike": 19.89,
                     "visibility": 10000,
                     "windSpeed": 3.08,
                     "cloudPercentage": 0,
                     "icon": "01d",
                     "advice": "clear sky"
                   },
                   {
                     "dtTxt": "2025-01-22 06:00:00",
                     "summary": "Clear",
                     "description": "clear sky",
                     "temp": 27.58,
                     "pressure": 1014,
                     "humidity": 21,
                     "tempMin": 27.58,
                     "tempMax": 27.58,
                     "tempFeelsLike": 26.49,
                     "visibility": 10000,
                     "windSpeed": 3.65,
                     "cloudPercentage": 0,
                     "icon": "01d",
                     "advice": "clear sky"
                   },
                   {
                     "dtTxt": "2025-01-22 09:00:00",
                     "summary": "Clear",
                     "description": "clear sky",
                     "temp": 29.58,
                     "pressure": 1010,
                     "humidity": 16,
                     "tempMin": 29.58,
                     "tempMax": 29.58,
                     "tempFeelsLike": 27.82,
                     "visibility": 10000,
                     "windSpeed": 3.69,
                     "cloudPercentage": 0,
                     "icon": "01d",
                     "advice": "clear sky"
                   },
                   {
                     "dtTxt": "2025-01-22 12:00:00",
                     "summary": "Clear",
                     "description": "clear sky",
                     "temp": 23.25,
                     "pressure": 1011,
                     "humidity": 22,
                     "tempMin": 23.25,
                     "tempMax": 23.25,
                     "tempFeelsLike": 22.21,
                     "visibility": 10000,
                     "windSpeed": 3.56,
                     "cloudPercentage": 0,
                     "icon": "01n",
                     "advice": "clear sky"
                   },
                   {
                     "dtTxt": "2025-01-22 15:00:00",
                     "summary": "Clear",
                     "description": "clear sky",
                     "temp": 19.91,
                     "pressure": 1013,
                     "humidity": 25,
                     "tempMin": 19.91,
                     "tempMax": 19.91,
                     "tempFeelsLike": 18.61,
                     "visibility": 10000,
                     "windSpeed": 3.47,
                     "cloudPercentage": 0,
                     "icon": "01n",
                     "advice": "Cool weather, wear a light jacket!"
                   },
                   {
                     "dtTxt": "2025-01-22 18:00:00",
                     "summary": "Clear",
                     "description": "clear sky",
                     "temp": 17.8,
                     "pressure": 1013,
                     "humidity": 31,
                     "tempMin": 17.8,
                     "tempMax": 17.8,
                     "tempFeelsLike": 16.45,
                     "visibility": 10000,
                     "windSpeed": 1.44,
                     "cloudPercentage": 0,
                     "icon": "01n",
                     "advice": "Cool weather, wear a light jacket!"
                   },
                   {
                     "dtTxt": "2025-01-22 21:00:00",
                     "summary": "Clear",
                     "description": "clear sky",
                     "temp": 17.06,
                     "pressure": 1012,
                     "humidity": 33,
                     "tempMin": 17.06,
                     "tempMax": 17.06,
                     "tempFeelsLike": 15.68,
                     "visibility": 10000,
                     "windSpeed": 1.15,
                     "cloudPercentage": 0,
                     "icon": "01n",
                     "advice": "Cool weather, wear a light jacket!"
                   },
                   {
                     "dtTxt": "2025-01-23 00:00:00",
                     "summary": "Clear",
                     "description": "clear sky",
                     "temp": 16.28,
                     "pressure": 1013,
                     "humidity": 36,
                     "tempMin": 16.28,
                     "tempMax": 16.28,
                     "tempFeelsLike": 14.9,
                     "visibility": 10000,
                     "windSpeed": 1.19,
                     "cloudPercentage": 2,
                     "icon": "01n",
                     "advice": "Cool weather, wear a light jacket!"
                   },
                   {
                     "dtTxt": "2025-01-23 03:00:00",
                     "summary": "Clear",
                     "description": "clear sky",
                     "temp": 22.21,
                     "pressure": 1015,
                     "humidity": 27,
                     "tempMin": 22.21,
                     "tempMax": 22.21,
                     "tempFeelsLike": 21.19,
                     "visibility": 10000,
                     "windSpeed": 0.43,
                     "cloudPercentage": 2,
                     "icon": "01d",
                     "advice": "clear sky"
                   },
                   {
                     "dtTxt": "2025-01-23 06:00:00",
                     "summary": "Clear",
                     "description": "clear sky",
                     "temp": 28.25,
                     "pressure": 1013,
                     "humidity": 19,
                     "tempMin": 28.25,
                     "tempMax": 28.25,
                     "tempFeelsLike": 26.89,
                     "visibility": 10000,
                     "windSpeed": 1.35,
                     "cloudPercentage": 1,
                     "icon": "01d",
                     "advice": "clear sky"
                   },
                   {
                     "dtTxt": "2025-01-23 09:00:00",
                     "summary": "Clear",
                     "description": "clear sky",
                     "temp": 30.22,
                     "pressure": 1010,
                     "humidity": 16,
                     "tempMin": 30.22,
                     "tempMax": 30.22,
                     "tempFeelsLike": 28.33,
                     "visibility": 10000,
                     "windSpeed": 3.19,
                     "cloudPercentage": 0,
                     "icon": "01d",
                     "advice": "clear sky"
                   },
                   {
                     "dtTxt": "2025-01-23 12:00:00",
                     "summary": "Clear",
                     "description": "clear sky",
                     "temp": 24.66,
                     "pressure": 1010,
                     "humidity": 24,
                     "tempMin": 24.66,
                     "tempMax": 24.66,
                     "tempFeelsLike": 23.81,
                     "visibility": 10000,
                     "windSpeed": 2.24,
                     "cloudPercentage": 7,
                     "icon": "01n",
                     "advice": "clear sky"
                   },
                   {
                     "dtTxt": "2025-01-23 15:00:00",
                     "summary": "Clear",
                     "description": "clear sky",
                     "temp": 20.77,
                     "pressure": 1013,
                     "humidity": 30,
                     "tempMin": 20.77,
                     "tempMax": 20.77,
                     "tempFeelsLike": 19.69,
                     "visibility": 10000,
                     "windSpeed": 3.06,
                     "cloudPercentage": 1,
                     "icon": "01n",
                     "advice": "clear sky"
                   },
                   {
                     "dtTxt": "2025-01-23 18:00:00",
                     "summary": "Clear",
                     "description": "clear sky",
                     "temp": 19.35,
                     "pressure": 1012,
                     "humidity": 34,
                     "tempMin": 19.35,
                     "tempMax": 19.35,
                     "tempFeelsLike": 18.23,
                     "visibility": 10000,
                     "windSpeed": 1.31,
                     "cloudPercentage": 5,
                     "icon": "01n",
                     "advice": "Cool weather, wear a light jacket!"
                   },
                   {
                     "dtTxt": "2025-01-23 21:00:00",
                     "summary": "Clear",
                     "description": "clear sky",
                     "temp": 18.55,
                     "pressure": 1011,
                     "humidity": 36,
                     "tempMin": 18.55,
                     "tempMax": 18.55,
                     "tempFeelsLike": 17.4,
                     "visibility": 10000,
                     "windSpeed": 0.71,
                     "cloudPercentage": 4,
                     "icon": "01n",
                     "advice": "Cool weather, wear a light jacket!"
                   },
                   {
                     "dtTxt": "2025-01-24 00:00:00",
                     "summary": "Clear",
                     "description": "clear sky",
                     "temp": 17.75,
                     "pressure": 1011,
                     "humidity": 37,
                     "tempMin": 17.75,
                     "tempMax": 17.75,
                     "tempFeelsLike": 16.55,
                     "visibility": 10000,
                     "windSpeed": 0.8,
                     "cloudPercentage": 3,
                     "icon": "01n",
                     "advice": "Cool weather, wear a light jacket!"
                   },
                   {
                     "dtTxt": "2025-01-24 03:00:00",
                     "summary": "Clear",
                     "description": "clear sky",
                     "temp": 23.35,
                     "pressure": 1013,
                     "humidity": 28,
                     "tempMin": 23.35,
                     "tempMax": 23.35,
                     "tempFeelsLike": 22.47,
                     "visibility": 10000,
                     "windSpeed": 1.23,
                     "cloudPercentage": 2,
                     "icon": "01d",
                     "advice": "clear sky"
                   },
                   {
                     "dtTxt": "2025-01-24 06:00:00",
                     "summary": "Clear",
                     "description": "clear sky",
                     "temp": 29.49,
                     "pressure": 1012,
                     "humidity": 19,
                     "tempMin": 29.49,
                     "tempMax": 29.49,
                     "tempFeelsLike": 27.81,
                     "visibility": 10000,
                     "windSpeed": 1.15,
                     "cloudPercentage": 1,
                     "icon": "01d",
                     "advice": "clear sky"
                   },
                   {
                     "dtTxt": "2025-01-24 09:00:00",
                     "summary": "Clear",
                     "description": "clear sky",
                     "temp": 30.68,
                     "pressure": 1008,
                     "humidity": 16,
                     "tempMin": 30.68,
                     "tempMax": 30.68,
                     "tempFeelsLike": 28.7,
                     "visibility": 10000,
                     "windSpeed": 4.19,
                     "cloudPercentage": 0,
                     "icon": "01d",
                     "advice": "clear sky"
                   },
                   {
                     "dtTxt": "2025-01-24 12:00:00",
                     "summary": "Clear",
                     "description": "clear sky",
                     "temp": 25.01,
                     "pressure": 1009,
                     "humidity": 23,
                     "tempMin": 25.01,
                     "tempMax": 25.01,
                     "tempFeelsLike": 24.17,
                     "visibility": 10000,
                     "windSpeed": 2.97,
                     "cloudPercentage": 0,
                     "icon": "01n",
                     "advice": "clear sky"
                   },
                   {
                     "dtTxt": "2025-01-24 15:00:00",
                     "summary": "Clear",
                     "description": "clear sky",
                     "temp": 20.98,
                     "pressure": 1012,
                     "humidity": 31,
                     "tempMin": 20.98,
                     "tempMax": 20.98,
                     "tempFeelsLike": 19.94,
                     "visibility": 10000,
                     "windSpeed": 3.93,
                     "cloudPercentage": 0,
                     "icon": "01n",
                     "advice": "clear sky"
                   },
                   {
                     "dtTxt": "2025-01-24 18:00:00",
                     "summary": "Clear",
                     "description": "clear sky",
                     "temp": 18.26,
                     "pressure": 1012,
                     "humidity": 44,
                     "tempMin": 18.26,
                     "tempMax": 18.26,
                     "tempFeelsLike": 17.29,
                     "visibility": 10000,
                     "windSpeed": 3.55,
                     "cloudPercentage": 0,
                     "icon": "01n",
                     "advice": "Cool weather, wear a light jacket!"
                   },
                   {
                     "dtTxt": "2025-01-24 21:00:00",
                     "summary": "Clear",
                     "description": "clear sky",
                     "temp": 16.37,
                     "pressure": 1011,
                     "humidity": 55,
                     "tempMin": 16.37,
                     "tempMax": 16.37,
                     "tempFeelsLike": 15.5,
                     "visibility": 10000,
                     "windSpeed": 3.54,
                     "cloudPercentage": 0,
                     "icon": "01n",
                     "advice": "Cool weather, wear a light jacket!"
                   },
                   {
                     "dtTxt": "2025-01-25 00:00:00",
                     "summary": "Clear",
                     "description": "clear sky",
                     "temp": 15.09,
                     "pressure": 1012,
                     "humidity": 61,
                     "tempMin": 15.09,
                     "tempMax": 15.09,
                     "tempFeelsLike": 14.25,
                     "visibility": 10000,
                     "windSpeed": 3.79,
                     "cloudPercentage": 0,
                     "icon": "01n",
                     "advice": "Cool weather, wear a light jacket!"
                   },
                   {
                     "dtTxt": "2025-01-25 03:00:00",
                     "summary": "Clear",
                     "description": "clear sky",
                     "temp": 19.46,
                     "pressure": 1014,
                     "humidity": 45,
                     "tempMin": 19.46,
                     "tempMax": 19.46,
                     "tempFeelsLike": 18.64,
                     "visibility": 10000,
                     "windSpeed": 5.27,
                     "cloudPercentage": 0,
                     "icon": "01d",
                     "advice": "Cool weather, wear a light jacket!"
                   },
                   {
                     "dtTxt": "2025-01-25 06:00:00",
                     "summary": "Clear",
                     "description": "clear sky",
                     "temp": 25.78,
                     "pressure": 1012,
                     "humidity": 26,
                     "tempMin": 25.78,
                     "tempMax": 25.78,
                     "tempFeelsLike": 25.09,
                     "visibility": 10000,
                     "windSpeed": 5.55,
                     "cloudPercentage": 0,
                     "icon": "01d",
                     "advice": "clear sky"
                   },
                   {
                     "dtTxt": "2025-01-25 09:00:00",
                     "summary": "Clear",
                     "description": "clear sky",
                     "temp": 27.49,
                     "pressure": 1009,
                     "humidity": 19,
                     "tempMin": 27.49,
                     "tempMax": 27.49,
                     "tempFeelsLike": 26.38,
                     "visibility": 10000,
                     "windSpeed": 6.25,
                     "cloudPercentage": 0,
                     "icon": "01d",
                     "advice": "clear sky"
                   },
                   {
                     "dtTxt": "2025-01-25 12:00:00",
                     "summary": "Clear",
                     "description": "clear sky",
                     "temp": 21.59,
                     "pressure": 1010,
                     "humidity": 21,
                     "tempMin": 21.59,
                     "tempMax": 21.59,
                     "tempFeelsLike": 20.35,
                     "visibility": 10000,
                     "windSpeed": 4.5,
                     "cloudPercentage": 0,
                     "icon": "01d",
                     "advice": "clear sky"
                   }
                 ],
                 "city": "Ranchi",
                 "population": 846454,
                 "timezone": 19800,
                 "sunrise": 1737334919,
                 "sunset": 1737374215
               },
               "_links": {
                       "self": {
                           "href": "http://localhost:8080/weather?city=Ranchi"
                       }
                   }
             }
             """;
    public static final String SCHEMA_500 = """
            {
                      "cod": 500,
                      "message": "Internal server error"
                    }
            """;
    public static final String SCHEMA_404 = """
            {
                "cod": "404",
                "message": "City Not Found",
                "data": null,
                "_links": {
                    "try-with-city-which-exists": {
                        "href": "http://localhost:8080/weather?city={city}",
                        "templated": true
                    }
                }
            }
            """;
    public static final String SCHEMA_400 = """
            {
                "cod": "400",
                "message": "City name must only contain letters and spaces",
                "data": null,
                "_links": {
                    "try-with-valid-city-name": {
                        "href": "http://localhost:8080/weather?city={city}",
                        "templated": true
                    }
                }
            }
            """;
    public static final String SCHEMA_503 = """
            {
                 "cod": "503",
                 "message": "Service is currently unavailable. Please try again later.",
                 "data": null,
                 "_links": {
                     "try-after-some-time": {
                         "href": "http://localhost:8080/weather?city={city}",
                         "templated": true
                     }
                 }
            }
            """;
}